# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/organisms_data.ipynb (unless otherwise specified).

__all__ = ['all_organisms', 'import_fasta', 'import_uniprot_annotation']

# Cell
all_organisms = {
    'Human': {'fasta_name': 'human.fasta',
               'uniprot_name': 'preprocessed_uniprot_human.csv'
              },
    'Mouse': {'fasta_name': 'mouse.fasta',
               'uniprot_name': 'preprocessed_uniprot_mouse.csv'
              },
    'Rat': {'fasta_name': 'rat_[10116].fasta',
               'uniprot_name': 'preprocessed_uniprot_rat.csv'
              },
    'Cow': {'fasta_name': 'bovine_[9913].fasta',
               'uniprot_name': 'preprocessed_uniprot_bovine.csv'
              },
    'Zebrafish': {'fasta_name': 'zebrafish_[7955].fasta',
               'uniprot_name': 'preprocessed_uniprot_zebrafish.csv'
              },
    'Drosophila': {'fasta_name': 'drosophila_[7227].fasta',
               'uniprot_name': 'preprocessed_uniprot_drosophila.csv'
              },
    'Caenorhabditis elegans': {'fasta_name': 'celegans_[6239].fasta',
               'uniprot_name': 'preprocessed_uniprot_human.csv'
              },
    'Slime mold': {'fasta_name': 'slimemold_[44689].fasta',
               'uniprot_name': 'preprocessed_uniprot_slimemold.csv'
              },
    'Arabidopsis thaliana': {'fasta_name': 'arabidopsis_thaliana.fasta',
               'uniprot_name': 'preprocessed_uniprot_arabidopsis.csv'
              },
    'Rice': {'fasta_name': 'rice_[39947].fasta',
               'uniprot_name': 'preprocessed_uniprot_rice.csv'
              },
    'Escherichia coli': {'fasta_name': 'ecoli_[83333].fasta',
               'uniprot_name': 'preprocessed_uniprot_ecoli.csv'
              },
    'Bacillus subtilis': {'fasta_name': 'bsubtilis_[224308].fasta',
               'uniprot_name': 'preprocessed_uniprot_bsubtilis.csv'
              },
    'Saccharomyces cerevisiae': {'fasta_name': 'yeast_[559292].fasta',
               'uniprot_name': 'preprocessed_uniprot_yeast.csv'
              },
    'SARS-CoV': {'fasta_name': 'cov.fasta',
               'uniprot_name': 'preprocessed_uniprot_cov.csv'
              },
    'SARS-CoV2': {'fasta_name': 'cov2.fasta',
               'uniprot_name': 'preprocessed_uniprot_cov2.csv'
              }
}

# Cell
import os
import urllib.request
from pyteomics import fasta
import alphamap

GITHUB_URL_DATA_FOLDER = "https://raw.githubusercontent.com/MannLabs/alphamap/refs/heads/main/alphamap/data/"

BASE_PATH = os.path.dirname(os.path.abspath(alphamap.__file__))
DATA_PATH = os.path.join(BASE_PATH, '..', 'alphamap', 'data')

def import_fasta(organism: str):
    """
    Import fasta file for the selected organism.
    This downloads the file from github if not present.

    Args:
        organism (str): Organism for which the fasta file should be imported.
    Returns:
        fasta: Fasta file imported by pyteomics 'fasta.IndexedUniProt' for the selected organism.
    """
    if not organism in all_organisms.keys():
        raise ValueError(f"Organism {organism} is not available. Please select one of the following: {list(all_organisms.keys())}")

    fasta_file_name = all_organisms[organism]['fasta_name']

    file_path = _download_file(DATA_PATH, fasta_file_name)

    return fasta.IndexedUniProt(file_path)

# Cell
import os
import urllib.request
import shutil
import pandas as pd
def import_uniprot_annotation(organism: str):
    """
    Import uniprot annotation file for the selected organism.
    This downloads the file from github if not present.

    Args:
        organism (str): Organism for which the uniprot annotation should be imported.
    Returns:
        pd.DataFrame: Dataframe with the uniprot annotations for the selected organism.

    """
    if not organism in all_organisms.keys():
        raise ValueError(f"Organism {organism} is not available. Please select one of the following: {list(all_organisms.keys())}")

    uniprot_file_name = all_organisms[organism]['uniprot_name']

    file_path = _download_file(DATA_PATH, uniprot_file_name)

    return pd.read_csv(file_path)

import tempfile
def _download_file(data_path: str, file_name: str) -> str:
    """Download a file `file_name` from `data_path` (e.g. GitHub) if not present and return its local path.

    In case that it is not possible to download to the package-internal folder (e.g. due to permission issues),
    a temporary directory will be created and used as a target for downloading.
    """
    file_path = os.path.join(data_path, file_name)
    temp_dir_path = os.path.join(tempfile.gettempdir(), "alphamap_temp")
    temp_file_path = os.path.join(temp_dir_path, file_name)

    if os.path.exists(file_path):
        print(f"Using cached {file_path}")
        return file_path

    if os.path.exists(temp_file_path):
        print(f"Using cached {temp_file_path}")
        return temp_file_path

    github_file_url = os.path.join(GITHUB_URL_DATA_FOLDER, file_name)

    print(f"Downloading {github_file_url} ..")
    with urllib.request.urlopen(github_file_url) as response:
        try:
            _safe_download(file_path, response)
            return file_path
        except Exception as e:
            # in case the user has to rights to write to the package folder
            print(f"Exception {e}: falling back to temporary location '{temp_file_path}'. Depending on your OS, you will need to clean up manually.")
            os.makedirs(temp_dir_path, exist_ok=True)
            _safe_download(temp_file_path, response)

            return temp_file_path

def _safe_download(file_path: str, response) -> None:
    """Download a file from a response to a local path in a 'safe' manner by creating the destination file only after download is completed."""
    # TODO find a way to clean up failed downloads
    download_file_path = file_path + ".tmp"
    with open(download_file_path, 'wb') as out_file:
        print(f".. to {file_path} ..")
        shutil.copyfileobj(response, out_file)
    os.rename(download_file_path, file_path)
    print(".. done")