# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_spectronaut_data": "Importing.ipynb",
         "expandProteinIds": "Preprocessing.ipynb",
         "fastaError": "Preprocessing.ipynb",
         "pepPositionHelper": "Preprocessing.ipynb",
         "getPeptidePosition": "Preprocessing.ipynb",
         "getPTMsites": "Preprocessing.ipynb",
         "getModifications": "Preprocessing.ipynb",
         "formatInputData": "Preprocessing.ipynb"}

modules = ["importing.py",
           "preprocessing.py"]

doc_url = "https://ibludau.github.io/pepmap/"

git_url = "https://github.com/ibludau/pepmap/tree/master/"

def custom_doc_links(name): return None
