# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_spectronaut_data": "Importing.ipynb",
         "expand_protein_ids": "Preprocessing.ipynb",
         "pep_position_helper": "Preprocessing.ipynb",
         "get_peptide_position": "Preprocessing.ipynb",
         "get_ptm_sites": "Preprocessing.ipynb",
         "get_modifications": "Preprocessing.ipynb",
         "format_input_data": "Preprocessing.ipynb"}

modules = ["importing.py",
           "preprocessing.py"]

doc_url = "https://ibludau.github.io/pepmap/"

git_url = "https://github.com/ibludau/pepmap/tree/master/"

def custom_doc_links(name): return None
