# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"import_spectronaut_data": "Importing.ipynb",
         "expand_protein_ids": "Preprocessing.ipynb",
         "pep_position_helper": "Preprocessing.ipynb",
         "get_peptide_position": "Preprocessing.ipynb",
         "get_ptm_sites": "Preprocessing.ipynb",
         "get_modifications": "Preprocessing.ipynb",
         "format_input_data": "Preprocessing.ipynb",
         "ptm_shape_dict": "SequencePlot.ipynb",
         "get_plot_data": "SequencePlot.ipynb",
         "plot_single_peptide_traces": "SequencePlot.ipynb",
         "custom_color_palettes": "SequencePlot.ipynb",
         "uniprot_color_dict": "SequencePlot.ipynb",
         "plot_peptide_traces": "SequencePlot.ipynb",
         "extract_note": "Uniprot_integration.ipynb",
         "extract_note_end": "Uniprot_integration.ipynb",
         "resolve_unclear_position": "Uniprot_integration.ipynb",
         "extract_positions": "Uniprot_integration.ipynb",
         "preprocess_uniprot": "Uniprot_integration.ipynb",
         "uniprot_feature_dict": "Uniprot_integration.ipynb"}

modules = ["importing.py",
           "preprocessing.py",
           "sequenceplot.py",
           "uniprot_integration.py"]

doc_url = "https://ibludau.github.io/pepmap/"

git_url = "https://github.com/ibludau/pepmap/tree/master/"

def custom_doc_links(name): return None
