# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Importing.ipynb (unless otherwise specified).

__all__ = ['importSpectronautData']

# Cell
import pandas as pd
import re

def importSpectronautData(file):
    data = pd.read_csv(file, sep=',')
    data_sub = data[["PEP.AllOccurringProteinAccessions","EG.ModifiedSequence"]]
    data_sub["modified_sequence"] = data_sub.apply(lambda row: re.sub('_','',row["EG.ModifiedSequence"]), axis=1)
    data_sub["naked_sequence"] = data_sub.apply(lambda row: re.sub(r'\[.*?\]','',row["modified_sequence"]), axis=1)
    data_sub = data_sub.rename(columns={"PEP.AllOccurringProteinAccessions": "all_protein_ids"})
    input_data = data_sub[["all_protein_ids","modified_sequence","naked_sequence"]]
    input_data = input_data.drop_duplicates().reset_index(drop=True)
    return input_data