# AUTOGENERATED! DO NOT EDIT! File to edit: Preprocessing.ipynb (unless otherwise specified).

__all__ = ['formatInputData']

# Cell

def formatInputData(df, fasta, modification_exp):
    res = df.copy(deep=True)
    res = expandProteinIds(res)
    res = getPeptidePosition(res, fasta = fasta)
    res = getModifications(res, mod_reg = modification_exp)
    return res